services:
  otel-collector:
    build:
      context: ../..
      dockerfile: examples/newrelicapm/Dockerfile
    command: ["--config=/etc/otel-collector-config.yaml"]
    environment:
      - NEW_RELIC_OTLP_ENDPOINT
      - NEW_RELIC_API_KEY
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"

  app:
    build:
      dockerfile: DockerPetclinic
    environment:
      OTEL_SERVICE_NAME: "OpenTelemetry-NewRelic-APM-Demo"
      OTEL_LOGS_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_TRACES_SAMPLER: "parentbased_traceidratio"
      OTEL_TRACES_SAMPLER_ARG: "0.02"
      OTEL_METRIC_EXPORT_INTERVAL: 5000
      OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: delta
      # OTEL_EXPORTER_OTLP_METRICS_DEFAULT_HISTOGRAM_AGGREGATION: base2_exponential_bucket_histogram
    ports:
      - "8080:8080"
    depends_on:
      - otel-collector
