receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

processors:
  batch:
  newrelicapm:

exporters:
  logging:
    verbosity: normal
  otlphttp:
    endpoint: $NEW_RELIC_OTLP_ENDPOINT
    headers:
      api-key: $NEW_RELIC_API_KEY

connectors:
  newrelicapm:
  newrelicapm/metrics:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [newrelicapm, batch]
      exporters: [newrelicapm, otlphttp]
    metrics:
      receivers: [otlp, newrelicapm]
      processors: [newrelicapm, batch]
      exporters: [otlphttp, newrelicapm/metrics]
    metrics/apm:
      receivers: [newrelicapm/metrics]
      exporters: [otlphttp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
